### PR TITLE
Quote CFBundleName, CFBundleDisplayName, CFBundleExecutable

### LINKED ISSUE #17: Old-style plist parser: missing semicolon in dictionary on line 2. Parsing will be abandoned.
```
2020-07-13 10:51:35.982 rust-fruitbasket-test[5183:19013837] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 2. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2020-07-13 10:51:35.982 rust-fruitbasket-test[5183:19013837] There was an error parsing the Info.plist for the bundle at URL <0x7fee68001320>: NSCocoaErrorDomain - 3840
```

This happens when you use spaces in the name. Fruitbasket doesn't quote the name in the plist, causing the parser to get confused. When there are no spaces in the name, the plist parser doesn't get confused. When you put double quotes in the name (as in `"\"Fruitbasket Test\""`) it doesn't get confused because it's quoted in the plist, but then it names the app bundle with those quotes as well.

### PR DESCRIPTION
**Pull request by LoganDark**
Should fix #17

### CODE REVIEW

**Comment by LoganDark** [comment]
@mrmekon

**Comment by mrmekon** [comment]
Sorry for long delays this summer, I'm hiking and have minimal internet access.  I'll merge this now, and push a patch release to crates.io sometime in the coming weeks.

**Comment by LoganDark** [comment]
@mrmekon Progress on the push? I don't see any new releases on crates.io.

**Comment by mrmekon** [comment]
@LoganDark sorry it took so long!  0.9 is now pushed to crates.io, including your other two PRs.

**Comment by LoganDark** [comment]
> including your other two PRs.

:D

**Pull request merged**
