### PR TITLE
Launch bundle as subprocess

### LINKED ISSUE #19: Output from the child process is lost after trampoline
I just ran into an issue and it took me a while to figure out what was happening. In #15, @mrmekon helpfully points out that output from the child process is not piped to the original stdout/stderr of the parent process, which causes the output to essentially be lost. Debug prints cannot be seen when launching from IntelliJ, since the app is handed off to macOS and then the parent process terminated.

I'm opening this issue to both represent the issue I just had, and act as something for their pull request to close, because it's always nice to close a real issue with a pull request :D

### PR DESCRIPTION
**Pull request by zyllian**
Fixes #19, though I don't know enough about mac bundles to know if this might break something. Seems to work for me, anyway.

### CODE REVIEW

**Comment by mrmekon** [comment]
I'm leaving this open for reference, but it's too big of a PR to merge without testing and I don't currently use macOS anywhere.

**Comment by maaku** [comment]
Near as I can tell this is actually a very small change hidden inside a giant autofmt-mess of a commit. I can test this (and remove the autofmt since you say elsewhere you don't like that), but if you no longer use macOS does that mean this macOS-only crate is abandoned? Do you need a new maintainer?

**Comment by zyllian** [comment]
@maaku That's my bad, I hadn't noticed that rustfmt changed it before committing.

FYI you can disable that formatting with a `.rustfmt.toml` like this:

```toml
disable_all_formatting = true
```

**Comment by maaku** [comment]
Actually looking at this further I think it defeats the whole purpose of fruitbasket. It just relaunches the executable again (as a terminal-bound process) rather than using Cocoa to launch the app bundle.

**Comment by zyllian** [comment]
[Relevant section of changes for posterity](https://github.com/mrmekon/fruitbasket/pull/30/files#diff-5ae659a665ce6fff8362669ed65be563a25922125ecfbba5d324882fb8259de1L560-R561)

@maaku What would an application actually lose from this? The only thing I needed from it was application menus since they weren't working without fruitbasket and they continued working with this change.

If there's other things an application would lose from this change then it's a no-go, but I don't know what those could be.

**Comment by maaku** [comment]
From the README of this project:

> This allows access to features that require running from a bundle ( such as XPC services), self-installing into the Applications folder, registering your app with the system as a document type or URL handler, and various other features that are only available to bundled apps with unique identifiers.

**Comment by maaku** [comment]
Although maybe macOS is able to detect that you are running an executable contained within a bundle, and silently treats that as a Cocoa launch? Your experience with menus seems to indicate that. I don't actually know. I do like that you were able to get rid of the unsafe block of code entirely.

**Comment by zyllian** [comment]
@maaku As I understand it the application is already bundled, aside from my accidental formatting changes this only changes how it's launched. The change should probably be tested with something using more Cocoa features, but as far as I know once it's bundled it should just work.

**Pull request closed without merging**
